LmsWeb/urls.py
from django.contrib import admin
from django.urls import path, include
import lms.urls
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import include
from django.views.generic import RedirectView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include(lms.urls)),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'lms'


urlpatterns = [
    # 登录页
    path('', views.loginOfAll, name='loginOfAll'),
    # 学生端
    path('index', views.index, name='lms_index'),

    path('ins_index', views.ins_index, name='ins_index'),

    path('lab', views.lab, name='lab'),
    path('browseHistory', views.borrowHistory, name='borrowHistory'),
    path('ins_browseHistory', views.borrowInsHistory, name='borrowInsHistory'),
    path('userCentre', views.userCentre, name='userCentre'),
    path('changePassword', views.changePassword, name='changePassword'),
    path('about', views.about, name='about'),
    path('subAndBo/<int:medicine_id>', views.subAndBo, name='subAndBo'),

    path('ins_subAndBo/<int:ins_id>', views.ins_subAndBo, name='ins_subAndBo'),

    path('login/', views.loging, name='login'),
    path('logout/', views.logouting, name='logout'),
    path('register/', views.register, name='register'),
    path('detail/<int:medicineId>', views.medicineDetail, name='medicineDetail'),
    path('medicineSearch/', views.medicineSearch, name='medicineSearch'),
    path('user_info/',views.userInfo,name='userInfo'),

    path('download_file/<int:doc_id>',views.download_file,name='download_file'),
    # path('download_template1/',views.download_template1,name='download_template1'),
    # path('download_template2/',views.download_template2,name='download_template2'),
    # path('download_template3/',views.download_template3,name='download_template3'),


    # admin中的
    path('admin/chart1/', views.chart1, name='chart1'),
    path('admin/chart2/', views.chart2, name='chart2'),
    path('admin/predict/', views.predict, name='predict'),
]

lms/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Lab(models.Model):
    """实验室表"""

    class Meta:
        verbose_name = '实验室'
        verbose_name_plural = verbose_name

    name = models.CharField('实验室名', max_length=20)
    description = models.TextField('实验室描述', blank=True)

    def __str__(self):
        return self.name


class Medicine(models.Model):
    """药品表"""

    class Meta:
        verbose_name = '药品列表'
        verbose_name_plural = verbose_name
        ordering = ('number',)

    # 药品信息类
    number = models.CharField('药品编号', max_length=13, unique=True)
    name = models.CharField('药品名', max_length=200)
    detail = models.TextField('药品信息', max_length=2000, blank=True)
    nowtotal = models.IntegerField('药品剩余量', default=0)
    usedtotal = models.IntegerField('药品用量', default=0)
    riskfactor = models.IntegerField('风险因子', default=0)

    def __str__(self):
        return self.name


class Instrument(models.Model):
    "2/28填装药品的仪器表"

    class Meta:
        verbose_name = '仪器列表'
        verbose_name_plural = verbose_name
        ordering = ('ins_no',)

    # 仪器信息
    ins_no = models.CharField('仪器编号', max_length=13, unique=True)
    ins_name = models.CharField('仪器名称', max_length=200)
    ins_detail = models.TextField('仪器信息', max_length=2000, blank=True)
    ins_nowtotal = models.IntegerField('仪器剩余数', default=0)
    ins_bototal = models.IntegerField('仪器借用数', default=0)

    def __str__(self):
        return self.ins_name


class CommonUser(models.Model):
    """学生表"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickyName = models.CharField('昵称', blank=True, max_length=50)
    cate = models.BooleanField('类别', default=False)
    # False stands for students, True represent Teacher
    faculty = models.CharField('系别', max_length=20, blank=True, default='undefine')

    class Meta:
        verbose_name = '学生信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.user)


class Borrow(models.Model):
    """借用药品纪录表"""

    class Meta:
        verbose_name = '借用药品记录'
        verbose_name_plural = verbose_name

    user = models.ForeignKey(CommonUser, on_delete=models.CASCADE, verbose_name='借用人')
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE, verbose_name='借用地点')
    medicine = models.ForeignKey(Medicine, on_delete=models.CASCADE, verbose_name='借用药品', )
    medicineUsedNum = models.PositiveIntegerField('药品使用量(/g)', default=0)
    boDate = models.DateTimeField('借用时间', auto_now_add=True)


class InsBorrow(models.Model):
    """2/28借用仪器纪录表"""

    class Meta:
        verbose_name = '借用仪器记录'
        verbose_name_plural = verbose_name

    ins_user = models.ForeignKey(CommonUser, on_delete=models.CASCADE, verbose_name='借用人')
    instrument = models.ForeignKey(Instrument, on_delete=models.CASCADE, verbose_name='借用仪器', )
    ins_boNum = models.PositiveIntegerField('借用数量', default=0)
    ins_boDate = models.DateTimeField('借用时间', auto_now_add=True)


class Doc(models.Model):
    class Meta:
        verbose_name = '文件'
        verbose_name_plural = verbose_name

    #  文件名称
    file_name = models.CharField('文件名字', max_length=50)
    #  文件保存路径
    file_path = models.CharField('文件路径', max_length=100)
    # 文件
    file_obj = models.FileField('文件', upload_to='files/')
    #  上传时间
    upload_time = models.DateTimeField('借用时间', auto_now_add=True)

    def __str__(self):
        return self.file_name

lms/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

from lms import models
from lms.models import Borrow


class UserCustomRegister(UserCreationForm):
    nickyName = forms.CharField(required=False, max_length=50)
    cate = forms.BooleanField(required=True)
    faculty = forms.CharField(required=True, max_length=20)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email',
                  'nickyName', 'cate', 'faculty')


class UserCustomChange(UserChangeForm):
    nickyName = forms.CharField(required=False, max_length=50)

    class Meta:
        model = User
        fields = ('email', 'password', 'nickyName')

lms/views.py
import datetime
import json
import os
import requests
from dateutil.relativedelta import relativedelta
from django.db import connection
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.core.paginator import Paginator, PageNotAnInteger, InvalidPage, EmptyPage
from django.db.models import Q, Count
from django.http import HttpResponse, JsonResponse, FileResponse, Http404
from django.shortcuts import render, redirect, reverse
# Create your views here.
from django.utils.encoding import escape_uri_path

from .models import *
from django.contrib.auth import authenticate, login, logout
from .forms import UserCustomRegister, UserCustomChange
from django.contrib.auth.models import User


# 总的登录界面
def loginOfAll(request):
    return render(request, 'lms/loginOfAll.html')


def index(request):
    if request.method == 'GET':
        MedicineList = Medicine.objects.all()
        LabList = Lab.objects.all()
        # 将数据按照规定每页显示 8 条, 进行分割
        paginator = Paginator(MedicineList, 8)

        # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')
        medicineList = paginator.get_page(page)

        # try:
        #     medicineList = paginator.page(page)
        # # todo: 注意捕获异常
        # except PageNotAnInteger:
        #     # 如果请求的页数不是整数, 返回第一页。
        #     medicineList = paginator.page(1)
        # except EmptyPage:
        #     # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
        #     medicineList = paginator.page(paginator.num_pages)
        # except InvalidPage:
        #     # 如果请求的页数不存在, 重定向页面
        #     return HttpResponse('找不到页面的内容')

        content = {
            'medicineList': medicineList,
            'LabList': LabList,
            'currentUser': request.user,
        }

        return render(request, 'lms/index.html', content)


def lab(request):
    LabList = Lab.objects.all()

    # 将数据按照规定每页显示 10 条, 进行分割
    paginator = Paginator(LabList, 10)

    # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
    page = request.GET.get('page')

    try:
        labList = paginator.page(page)
    # todo: 注意捕获异常
    except PageNotAnInteger:
        # 如果请求的页数不是整数, 返回第一页。
        labList = paginator.page(1)
    except EmptyPage:
        # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
        labList = paginator.page(paginator.num_pages)
    except InvalidPage:
        # 如果请求的页数不存在, 重定向页面
        return HttpResponse('找不到页面的内容')
    content = {
        'labList': labList,

    }
    return render(request, 'lms/lab.html', content)


def about(request):
    if request.method == 'GET':
        docList = Doc.objects.all()

        return render(request, 'lms/about.html', locals())


def medicineSearch(request):
    """
    注意这里的 MedicineList 与分页 medicineList不能同名

    """
    LabList = Lab.objects.all()

    if request.method == 'POST':
        searchType = request.POST['searchType']
        keyword = request.POST['keyword']
        # print(searchType, keyword)
        if searchType == 'name':
            MedicineList = Medicine.objects.filter(name__contains=keyword)
            # print("ky1:" + str(medicineList))

        elif searchType == 'number':
            MedicineList = Medicine.objects.filter(number__contains=keyword)
            # print("ky2：" + str(medicineList))

        else:
            # print("xixxixiix")
            MedicineList = Medicine.objects.filter(Q(name__contains=keyword) |
                                                   Q(number__contains=keyword))
            # print("ky3:" + str(medicineList))

        # 将数据按照规定每页显示 8 条, 进行分割
        paginator = Paginator(MedicineList, 8)

        # 获取 url 后面的 page 参数的值, 首页不显示 page 参数, 默认值是 1
        page = request.GET.get('page')

        medicineList = paginator.get_page(page)
        # try:
        #     # medicineList = paginator.page(page)
        #     medicineList = paginator.get_page(page)
        # # todo: 注意捕获异常
        # except PageNotAnInteger:
        #     # 如果请求的页数不是整数, 返回第一页。
        #     medicineList = paginator.get_page(1)
        # except EmptyPage:
        #     # 如果请求的页数不在合法的页数范围内，返回结果的最后一页。
        #     medicineList = paginator.get_page(paginator.num_pages)
        # except InvalidPage:
        #     # 如果请求的页数不存在, 重定向页面
        #     return HttpResponse('找不到页面的内容')

        content = {'medicineList': medicineList,
                   'LabList': LabList,
                   'currentUser': request.user
                   }
        return render(request, 'lms/index.html', content)


# 登陆注册

def loging(request):
    # 登录模块
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'lms/login.html', {'error': '用户名不存在或密码错误'})
        else:
            login(request, user)
            return redirect('lms:lms_index')
    else:
        return render(request, 'lms/login.html')


# 登出
def logouting(request):
    logout(request)
    return redirect('lms:lms_index')


# 注册
def register(request):
    if request.method == 'POST':
        registerForm = UserCustomRegister(request.POST)
        if registerForm.is_valid():
            registerForm.save()
            newUser = authenticate(username=registerForm.cleaned_data['username'],
                                   password=registerForm.cleaned_data['password1'])
            newUser.email = registerForm.cleaned_data['email']
            CommonUser(user=newUser, nickyName=registerForm.cleaned_data['nickyName'],
                       cate=registerForm.cleaned_data['cate'],
                       faculty=registerForm.cleaned_data['faculty']).save()
            login(request, newUser)
            return redirect('lms:lms_index')
    else:

        registerForm = UserCustomRegister()
    content = {'registerForm': registerForm}
    return render(request, 'lms/register.html', content)


# 学生信息
@login_required(login_url='lms:login')
def userCentre(request):
    # need id to define special user
    if request.method == 'POST':
        changeForm = UserCustomChange(request.POST, instance=request.user)
        if changeForm.is_valid():
            changeForm.save()
            request.user.commonuser.nickyName = changeForm.cleaned_data['nickyName']
            request.user.commonuser.save()
            # 关联的表要另外存储
            # newUser.email = registerForm.cleaned_data['email']
            # CommonUser(user=newUser, nickyName=registerForm.cleaned_data['nickyName'],
            #            cate=registerForm.cleaned_data['cate'],
            #            faculty=registerForm.cleaned_data['faculty']).save()
    else:
        pass
    changeForm = UserCustomChange()
    content = {'currentUser': request.user, 'changeForm': changeForm}
    return render(request, 'lms/userCentre.html', content)


# 学生修改密码
@login_required(login_url='lms:login')
def changePassword(request):
    if request.method == 'POST':
        changepasswordForm = PasswordChangeForm(data=request.POST, user=request.user)
        if changepasswordForm.is_valid():
            changepasswordForm.save()
            return redirect('lms:login')
    else:
        pass
    changepasswordForm = PasswordChangeForm(user=request.user)
    content = {
        'currentUser': request.user,
        'changepasswordForm': changepasswordForm
    }
    return render(request, 'lms/changePassword.html', content)


# 学生借阅历史查看
@login_required(login_url='lms:login')
def borrowHistory(request):
    # need id to define special user
    if request.method == 'GET':
        user = CommonUser.objects.filter(user=request.user).first()
        MedicineListTarget = Borrow.objects.filter(user=user).order_by("-boDate")
        MedicineList = []
        for borrowInfo in MedicineListTarget:
            borrowTime = datetime.datetime.now().day - borrowInfo.boDate.day
            MedicineList.append((Medicine.objects.get(pk=borrowInfo.medicine_id), borrowInfo, borrowTime))

        # chart_info = Borrow.objects.filter(user=user).values_list('medicine').annotate(Count('id'))
        # print(chart_info)

        content = {
            'MedicineList': MedicineList,
            'currentUser': request.user
        }
        return render(request, 'lms/borrowHistory.html', content)


# 药品详情表
def medicineDetail(request, medicineId):
    if request.method == 'GET':
        thisMedicine = Medicine.objects.get(id=medicineId)
        content = {
            'medicine': thisMedicine,
        }
        return render(request, 'lms/detail.html', content)


#
@login_required(login_url='lms:login')
def subAndBo(request, medicine_id):
    LabList = Lab.objects.all()
    if request.method == 'POST':

        thisLab = request.POST.get('lab')
        print(thisLab)
        thisNum = int(request.POST.get('medicineUsedNum'))
        thisUser = User.objects.get(pk=request.user.id)
        # p判断实验室是否存在
        labTrue = Lab.objects.filter(name__exact=thisLab).count()
        print(labTrue)
        # if (thisLab == ''):
        #     thisLab = "ooo"
        #     得到了的Lab为空值？
        # print(thisLab, thisNum, thisUser)
        thisMedicine = Medicine.objects.get(pk=medicine_id)
        # print(medicine_id)
        if thisMedicine.nowtotal <= thisNum:
            # return HttpResponse("失败！库存不足！")
            # return JsonResponse({"failInfo": "失败！库存不足！"})
            return render(request, 'lms/error.html', {"failInfo": "失败！库存不足！"})


        elif labTrue == 0:
            return render(request, 'lms/error.html', {"failInfo": "请输入正确的实验室名称"})

            # return HttpResponse("请输入正确的实验室名称")

        else:
            thisMedicine.usedtotal += thisNum
            thisMedicine.nowtotal -= thisNum
            thisMedicine.save()
            newBorrow = Borrow(user=thisUser.commonuser, lab=Lab.objects.get(name=thisLab),
                               medicine=thisMedicine, medicineUsedNum=thisNum)
            newBorrow.save()

            # content = {

lms/templates/lms/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keyword" content="{% block keyword %}BASE_HTML{% endblock %}">
    <meta name="description" content="{% block description %}BASE_HTML{% endblock %}">
    <meta name="author" content="skywalker">
    <link rel="icon" href="{% static 'lms/icons/baseIcon.png' %}">
    <title>实验室药品分析与预警系统
        {% block title %}
        {% endblock %}
    </title>


    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'lms/css/bootstrap.min.css' %}">
    {#<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">#}
    {#<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>#}
    {#    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">#}
    {#    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>#}


    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'lms/css/base.css' %}">
    {# 插入bass.css#}
    <link rel="stylesheet" href="{% block css %}
    {% endblock css %}">
    {# css of each site   #}


</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <img src="{% static 'lms/icons/login1.png' %}"
         width="33" height="33" class="d-inline-block align-top" alt="">
    <a class="navbar-brand" href="#">ChemLab</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
            aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item  {% block indexHighlight %}{% endblock %}">
                <a class="nav-link" href="{% url 'lms:lms_index' %}">药品列表 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item  {% block insindexHighlight %}{% endblock %}">
                <a class="nav-link" href="{% url 'lms:ins_index' %}">仪器列表 <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item  {% block labHighlight %}{% endblock %}">
                <a class="nav-link" href="{% url 'lms:lab' %}">实验室列表<span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item {% block userHighlight %}{% endblock %}">
                <a class="nav-link" href="{% url 'lms:userInfo' %}">个人中心</a>
            </li>


            {#            <li class="nav-item dropdown">#}
            {#                <a class="nav-link dropdown-toggle" id="userInfo" data-toggle="dropdown"#}
            {#                   aria-haspopup="true" aria-expanded="false" href="#">个人中心</a>#}
            {#                <div class="dropdown-menu" aria-labelledby="userInfo">#}
            {#                    <a class="dropdown-item" href="{% url 'lms:userCentre' %}">个人信息</a>#}
            {#                    <a class="dropdown-item" href="{% url 'lms:borrowHistory' %}">借阅历史</a>#}
            {#                    <a class="dropdown-item" href="{% url 'lms:changePassword' %}">修改密码</a>#}
            {#                </div>#}
            {#            </li>#}


            {#            <li class="nav-item {% block aboutHighlight %}{% endblock %}">#}
            {#                <a class="nav-link disabled" href="{% url 'lms:about' %}">关于</a>#}
            {#            </li>#}
            <li class="nav-item {% block aboutHighlight %}{% endblock %}">
                <a class="nav-link disabled" href="{% url 'lms:about' %}">关于</a>
            </li>

            {#        test chart1#}
            {#            <li class="nav-item" >#}
            {#                <a class="nav-link disabled" href="{% url 'lms:chart1' %}">chart</a>#}
            {#            </li>#}

        </ul>

        <form class="form-inline my-2 my-lg-0" action="{% url 'lms:medicineSearch' %}" method="POST">
            {% csrf_token %}
            <input name='keyword' class="form-control mr-sm-2" type="text" placeholder="请输入要查询的药品" aria-label="Search">
            <div class="form-row align-items-center">
                <div class="col-auto my-1">
                    <label class="mr-sm-2 sr-only" for="inlineFormCustomSelect">Preference</label>
                    <select name='searchType' class="custom-select mr-sm-2" id="inlineFormCustomSelect">
                        <option selected>所有</option>
                        <option value="name">药品名</option>
                        <option value="number">药品编号</option>
                    </select>
                </div>
            </div>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
        </form>

        {% if user.is_authenticated %}
            <a href="{% url 'lms:logout' %}">
                <button class="btn btn-primary">登出</button>
            </a>
            </div>
        {% else %}
            <a href="{% url 'lms:login' %}">
                <button class="btn btn-primary">登录</button>
            </a>
            </div>
        {% endif %}
</nav>


<main role="main" class="container">
    {% block main_block %}
        基础主体部分
    {% endblock %}
    <!-- /.container -->

</main>
<footer class="footer">
    <div class="text-center">
        <a href="https://gitee.com/zcystart/chemlab.git">&copy;Lab 2021</a>
    </div>
</footer>


<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
{#<script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js"#}
{#        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"#}
{#        crossorigin="anonymous"></script>#}
<script src="{% static 'lms/js/bootstrap.min.js' %}"></script>

</body>
</html>

lms/templates/lms/register.html
<!DOCTYPE html>
{% extends 'lms/base.html' %}
{% load static %}

{% block title %}
    -注册
{% endblock %}

{% block css %}

{% endblock %}

{% block main_block %}

    {% if registerForm.errors %}
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">注册出现问了哦</h4>
            <p>{{ registerForm.errors }}</p>
            <hr>
            <p class="mb-0">请再次注册</p>
        </div>
    {% endif %}

    <script type="text/javascript">

        function name() {
            var username = document.getElementById("id_username");
            var usernametext = username.value;
            //验证字符串符合规则
            var patt = /^\d{8}$/;
            /*test方法用于测试字符串是否匹配规则*/
            if (patt.test(usernametext)) {

            } else {
                alert("学号不合法！")
            }

        }
    </script>

    <form class="form-group registerForm" action="" method="POST">
        {% csrf_token %}
        <p>
            <label for="id_username">学号:</label>
            <input class="form-control" type="text" name="username" maxlength="8" autofocus required
                   id="id_username" value="">
            <small class="form-text text-muted">必填。8位学号</small>
        </p>
        <p>
            <label for="id_nickyName">Nickyname:</label>
            <input class="form-control" type="text" name="nickyName" maxlength="50"
                   id="id_nickyName">
        </p>
        <p>
            <label for="id_password1">密码:</label>
            <input class="form-control" type="password" name="password1" required id="id_password1">
            <small class="form-text text-muted">
                <ul>
                    <li>你的密码不能与其他个人信息太相似。</li>
                    <li>你的密码必须包含至少 8 个字符。</li>
                    <li>你的密码不能是大家都爱用的常见密码。</li>
                    <li>你的密码不能全部为数字。</li>
                </ul>
            </small>
        </p>
        <p><label for="id_password2">密码确认:</label>
            <input class="form-control" type="password" name="password2" required id="id_password2">
            <small class="form-text text-muted">为了校验，请输入与上面相同的密码。</small>
        </p>
        <p>
            <label for="id_email">电子邮件地址:</label>
            <input class="form-control" type="email" name="email" maxlength="254" id="id_email"></p>

        <p>
            <label class="form-check-label" for="id_cate">Cate:</label>
            <input type="checkbox" name="cate" required id="id_cate">
            <small class="form-text text-muted">勾选表明为学生用户，不勾选为教师用户</small>
        </p>
        <p>
            <label for="id_faculty">Faculty:</label>
            <input class="form-control" type="text" name="faculty" maxlength="20" required id="id_faculty">
            <small class="form-text text-muted">请输入您的学院</small>
        </p>
        <button class="btn btn-primary" type="submit" onclick="name()">注册</button>
    </form>
{% endblock %}

lms/templates/lms/temp.html
<!DOCTYPE html>
{% extends 'lms/base.html' %}
{% load static %}

{#{% block css %}#}
{#{% static 'lms/css/browseHistory.css' %}#}
{#{% endblock %}#}

{% block main_block %}
{% endblock %}

lms/templates/lms/usr_info.html
<!DOCTYPE html>
{% extends 'lms/base.html' %}
{% load static %}

{% block title %}
    -用户信息
{% endblock %}

{% block css %}
    {% static 'lms/css/usr_info.css' %}
{% endblock %}





{% block main_block %}
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <section id="content" class="clearfix">
        <section class="light-buttons">
            <div class="right">
                <h1 class="dark-header">About you</h1>
                <a href="{% url 'lms:userCentre' %}" class="button lightbg-blue clearfix"><span>个人信息</span>
                    <div class="icon">
                        <div class="arrow"></div>
                    </div>
                </a><a href="{% url 'lms:borrowHistory' %}" class="button lightbg-pink clearfix"><span>借阅药品历史</span>
                <div class="icon">
                    <div class="arrow"></div>
                </div>
            </a> <a href="{% url 'lms:borrowInsHistory' %}" class="button lightbg-green clearfix"><span>借阅仪器历史</span>
                <div class="icon">
                    <div class="arrow"></div>
                </div>
            </a><a href="{% url 'lms:changePassword' %}" class="button lightbg-orange clearfix"><span>修改密码</span>
                <div class="icon">
                    <div class="arrow"></div>
                </div>
            </a>
            </div>
        </section>
    </section>



{% endblock %}